"""`fintrack migrate-legacy` — one-time import of the legacy databases."""

import os
from pathlib import Path

import click

from fintrack.core.config import PROJECT_ROOT
from fintrack.migrate.legacy import (
    MigrationError,
    apply_migration,
    load_mapping,
    render_mapping_template,
)


@click.command("migrate-legacy")
@click.option(
    "--spending-db",
    required=True,
    type=click.Path(exists=True, dir_okay=False, path_type=Path),
    help="Path to the legacy spending.db",
)
@click.option(
    "--finances-db",
    required=True,
    type=click.Path(exists=True, dir_okay=False, path_type=Path),
    help="Path to the legacy finances.db",
)
@click.option(
    "--mapping",
    required=True,
    type=click.Path(dir_okay=False, path_type=Path),
    help="Account mapping YAML (generated by --write-template, then reviewed)",
)
@click.option(
    "--write-template",
    is_flag=True,
    help="Scan both databases and write the mapping template to --mapping, then exit",
)
@click.option(
    "--db",
    "target_db",
    type=click.Path(dir_okay=False, path_type=Path),
    default=lambda: os.environ.get("FINTRACK_DB", "fintrack.db"),
    help="Target unified database (default: $FINTRACK_DB or fintrack.db)",
)
@click.option(
    "--dry-run",
    is_flag=True,
    help="Run the full migration in a transaction and roll back",
)
def migrate_legacy(
    spending_db, finances_db, mapping, write_template, target_db, dry_run
):
    """Merge the legacy spending and finances databases into one fintrack DB.

    Two-step flow: first --write-template to generate the account mapping,
    review/edit it, then run again (optionally with --dry-run first) to apply.
    Legacy databases are only read, never modified.
    """
    try:
        if write_template:
            if mapping.exists():
                raise MigrationError(
                    f"{mapping} already exists; delete it or pass a different path"
                )
            mapping.write_text(render_mapping_template(spending_db, finances_db))
            click.echo(f"Wrote mapping template to {mapping}")
            click.echo(
                "Review the merge_into/snapshot assignments, then rerun without --write-template."
            )
            return
        if not mapping.exists():
            raise MigrationError(
                f"Mapping file {mapping} not found; generate one with --write-template"
            )
        report = apply_migration(
            spending_db, finances_db, load_mapping(mapping), target_db, dry_run=dry_run
        )
        click.echo(report)
        if not dry_run:
            _stamp_alembic_head(target_db)
            click.echo(f"\nMigrated into {target_db} (alembic stamped at head).")
    except MigrationError as e:
        raise click.ClickException(str(e))


def _stamp_alembic_head(target_db: Path) -> None:
    """Mark the freshly created schema as current so future upgrades apply."""
    from alembic import command as alembic_command
    from alembic.config import Config

    os.environ["FINTRACK_DB"] = str(target_db)
    alembic_command.stamp(Config(str(PROJECT_ROOT / "alembic.ini")), "head")
