"""add asset return rate and contribution

Revision ID: a70203be0102
Revises: a1b2c3d4e5f6
Create Date: 2026-07-29 20:52:29.303502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a70203be0102'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_entries', sa.Column('annual_return_rate', sa.Numeric(precision=8, scale=6), nullable=True))
    op.add_column('asset_entries', sa.Column('monthly_contribution', sa.Numeric(precision=14, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table("asset_entries") as batch_op:
        batch_op.drop_column("monthly_contribution")
        batch_op.drop_column("annual_return_rate")
